[package]
name = "takegraph-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
png.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
takegraph-core = { path = "../takegraph-core" }
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
